// <auto-generated />
using BIKESobj.InfrastructureServices.Gateways.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BIKESobj.WebService.Migrations
{
    [DbContext(typeof(BIKESobjContext))]
    [Migration("20200603194403_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("BIKESobj.DomainObjects.bikesobj", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartamentalAffiliation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectOperOrgPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Width")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BIKESobjs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DepartamentalAffiliation = "Департамент жилищно-коммунального хозяйства и благоустройства города Москвы",
                            Location = "ТиНАО, посел. Первомайское, М-3 Украина- г.Троицк (М-1 Беларусь-Крекшино-Троицк)",
                            Name = "А/д Боровское шоссе – Киевское шоссе – д. Ботаково",
                            ObjectOperOrgPhone = "(495) 940-06-94",
                            Width = "1.8"
                        },
                        new
                        {
                            Id = 2L,
                            DepartamentalAffiliation = "Департамент культуры города Москвы",
                            Location = "улица Крымский Вал, дом 9",
                            Name = "Андреевская набережная, Природный заказник «Воробьёвы горы»",
                            ObjectOperOrgPhone = "(495) 995-00-20",
                            Width = "1.5"
                        },
                        new
                        {
                            Id = 3L,
                            DepartamentalAffiliation = "Департамент жилищно-коммунального хозяйства и благоустройства города Москвы",
                            Location = "Арбатская площадь",
                            Name = "Арбатская площадь",
                            ObjectOperOrgPhone = "(495) 940-06-94",
                            Width = "1.2"
                        },
                        new
                        {
                            Id = 4L,
                            DepartamentalAffiliation = "Префектура Северо-Восточного административного округа города Москвы",
                            Location = "от Олонецкой улицы дом 15Б до Березовой аллеи дом 7",
                            Name = "Березовая аллея",
                            ObjectOperOrgPhone = "(495) 708-44-69",
                            Width = "1"
                        },
                        new
                        {
                            Id = 5L,
                            DepartamentalAffiliation = "Префектура Северного административного округа города Москвы",
                            Location = "Бескудниковский район",
                            Name = "Бескудниковский бульвар (озелененная часть)",
                            ObjectOperOrgPhone = "(499) 487-04-90",
                            Width = "2.5"
                        },
                        new
                        {
                            Id = 6L,
                            DepartamentalAffiliation = "Департамент природопользования и охраны окружающей среды города Москвы",
                            Location = "в границах Бирюлевского дендропарка",
                            Name = "Бирюлевский дендропарк",
                            ObjectOperOrgPhone = "(499) 739-27-05",
                            Width = "1.5"
                        },
                        new
                        {
                            Id = 7L,
                            DepartamentalAffiliation = "Департамент жилищно-коммунального хозяйства и благоустройства города Москвы",
                            Location = "Боровское шоссе",
                            Name = "Боровское шоссе",
                            ObjectOperOrgPhone = "(495) 940-06-94",
                            Width = "1.2"
                        },
                        new
                        {
                            Id = 8L,
                            DepartamentalAffiliation = "Префектура Центрального административного округа города Москвы",
                            Location = "Бронная М. ул.",
                            Name = "Бронная М. ул.",
                            ObjectOperOrgPhone = "(495) 670-02-60",
                            Width = "1.2"
                        },
                        new
                        {
                            Id = 9L,
                            DepartamentalAffiliation = "Префектура Северного административного округа города Москвы",
                            Location = "Большая Академическая улица, дом 8-10",
                            Name = "Велодорожка",
                            ObjectOperOrgPhone = "(985) 640-80-67",
                            Width = "2.1"
                        },
                        new
                        {
                            Id = 10L,
                            DepartamentalAffiliation = "Префектура Северного административного округа города Москвы",
                            Location = "Большая Академическая улица, дом 14",
                            Name = "Велодорожка (в зоне озеленения)",
                            ObjectOperOrgPhone = "(985) 640-80-67",
                            Width = "2.1"
                        },
                        new
                        {
                            Id = 11L,
                            DepartamentalAffiliation = "Префектура Северного административного округа города Москвы",
                            Location = "Большая Академическая улица, дом 18",
                            Name = "Велодорожка (зона озеленения)",
                            ObjectOperOrgPhone = "(985) 640-80-67",
                            Width = "2.1"
                        },
                        new
                        {
                            Id = 12L,
                            DepartamentalAffiliation = "Префектура Западного административного округа города Москвы",
                            Location = "от улицы Славянский бульвар дом 15 до улицы Кременчугская дом 22",
                            Name = "Велодорожка в Кременчугском сквере",
                            ObjectOperOrgPhone = "(499) 792-65-06",
                            Width = "2"
                        },
                        new
                        {
                            Id = 13L,
                            DepartamentalAffiliation = "Префектура Западного административного округа города Москвы",
                            Location = "Парк школьников",
                            Name = "Велодорожка в Парке Школьников",
                            ObjectOperOrgPhone = "(499) 792-65-06",
                            Width = "2"
                        },
                        new
                        {
                            Id = 14L,
                            DepartamentalAffiliation = "Префектура Северного административного округа города Москвы",
                            Location = "Большая Академическая улица, дом 2",
                            Name = "Велодорожка в зоне озеленения",
                            ObjectOperOrgPhone = "(985) 640-80-67",
                            Width = "2.1"
                        },
                        new
                        {
                            Id = 15L,
                            DepartamentalAffiliation = "Префектура Троицкого и Новомосковского административных округов города Москвы",
                            Location = "г. Московский место массового отдыха населения между микрорайоном 3 и поселком института полиомиелита",
                            Name = "Велодорожка в месте массового отдыха населения г. Московский",
                            ObjectOperOrgPhone = "(495) 841-81-47",
                            Width = "1.5"
                        },
                        new
                        {
                            Id = 16L,
                            DepartamentalAffiliation = "Префектура Западного административного округа города Москвы",
                            Location = "улица Кравченко дом 7",
                            Name = "Велодорожка в парке Кравченские пруды",
                            ObjectOperOrgPhone = "(499) 792-65-06",
                            Width = "2"
                        },
                        new
                        {
                            Id = 17L,
                            DepartamentalAffiliation = "Префектура Юго-Восточного административного округа города Москвы",
                            Location = "Парк на набережной (по ул.Гурьянова)",
                            Name = "Велодорожка в парке на набережной (по ул.Гурьянова)",
                            ObjectOperOrgPhone = "(495) 657-35-00",
                            Width = "1.2"
                        },
                        new
                        {
                            Id = 18L,
                            DepartamentalAffiliation = "Префектура Северного административного округа города Москвы",
                            Location = "Большая Академическая улица, дом 45-49",
                            Name = "Велодорожка вблизи д. 45-49",
                            ObjectOperOrgPhone = "(985) 640-80-67",
                            Width = "2.1"
                        },
                        new
                        {
                            Id = 19L,
                            DepartamentalAffiliation = "Префектура Северного административного округа города Москвы",
                            Location = "Большая Академическая улица, дом 28",
                            Name = "Велодорожка вблизи дома 28",
                            ObjectOperOrgPhone = "(985) 640-80-67",
                            Width = "2.1"
                        },
                        new
                        {
                            Id = 20L,
                            DepartamentalAffiliation = "Префектура Северного административного округа города Москвы",
                            Location = "Большая Академическая улица, дом 51",
                            Name = "Велодорожка вблизи дома 51",
                            ObjectOperOrgPhone = "(985) 640-80-67",
                            Width = "2.1"
                        },
                        new
                        {
                            Id = 21L,
                            DepartamentalAffiliation = "Префектура Северного административного округа города Москвы",
                            Location = "Большая Академическая улица, дом 71",
                            Name = "Велодорожка вблизи дома 71",
                            ObjectOperOrgPhone = "(985) 640-80-67",
                            Width = "2.1"
                        },
                        new
                        {
                            Id = 22L,
                            DepartamentalAffiliation = "Префектура Северного административного округа города Москвы",
                            Location = "Большая Академическая улица, д. 77-79",
                            Name = "Велодорожка вблизи дома 77-79",
                            ObjectOperOrgPhone = "(985) 640-80-67",
                            Width = "2.1"
                        },
                        new
                        {
                            Id = 23L,
                            DepartamentalAffiliation = "Префектура Западного административного округа города Москвы",
                            Location = "Рублевское шоссе от дома 16 корпус 1 до дома 52 а",
                            Name = "Велодорожка вдоль дублера Рублевского шоссе",
                            ObjectOperOrgPhone = "(499) 792-65-06",
                            Width = "2"
                        },
                        new
                        {
                            Id = 24L,
                            DepartamentalAffiliation = "Префектура Северного административного округа города Москвы",
                            Location = "Авиаконструктора Микояна",
                            Name = "Велодорожка вдоль ул. Авиаконструктора Микояна",
                            ObjectOperOrgPhone = "(495) 940-08-83",
                            Width = "2.5"
                        },
                        new
                        {
                            Id = 25L,
                            DepartamentalAffiliation = "Префектура Западного административного округа города Москвы",
                            Location = "Ул. Лобачевского (от проспекта Вернадского до Мичуринского проспекта)",
                            Name = "Велодорожка вдоль улицы Лобачевского",
                            ObjectOperOrgPhone = "(499) 792-65-06",
                            Width = "1.5"
                        },
                        new
                        {
                            Id = 26L,
                            DepartamentalAffiliation = "Префектура Западного административного округа города Москвы",
                            Location = "улица Минская от дома 1 до железнодорожного моста",
                            Name = "Велодорожка вдоль улицы Минская",
                            ObjectOperOrgPhone = "(499) 792-65-06",
                            Width = "2"
                        },
                        new
                        {
                            Id = 27L,
                            DepartamentalAffiliation = "Префектура Западного административного округа города Москвы",
                            Location = "от улицы Улофе Пальме 3 до улицы Мосфильмовская",
                            Name = "Велодорожка вдоль улицы Улофа Пальме",
                            ObjectOperOrgPhone = "(495) 539-53-53",
                            Width = "2"
                        },
                        new
                        {
                            Id = 28L,
                            DepartamentalAffiliation = "Префектура Троицкого и Новомосковского административных округов города Москвы",
                            Location = "ул. Радужная, г. Московский",
                            Name = "Велодорожка на озелененной территории ул.Радужная, г. Московский",
                            ObjectOperOrgPhone = "(495) 841-81-47",
                            Width = "1.5"
                        },
                        new
                        {
                            Id = 29L,
                            DepartamentalAffiliation = "Префектура Северо-Западного административного округа города Москвы",
                            Location = "г. Москва, район Куркино, территория между мкр.15 и мкр.4.",
                            Name = "Велодорожка на территории между мкр.15 и мкр.4 Парк Дубрава",
                            ObjectOperOrgPhone = "(499) 744-88-11",
                            Width = "1.5"
                        },
                        new
                        {
                            Id = 30L,
                            DepartamentalAffiliation = "Префектура Южного административного округа города Москвы",
                            Location = "парк Фруктовый по Востряковскому проезду",
                            Name = "Велодорожка на территории парка Фруктовый",
                            ObjectOperOrgPhone = "(495) 384-05-00",
                            Width = "2.4"
                        },
                        new
                        {
                            Id = 31L,
                            DepartamentalAffiliation = "Префектура Южного административного округа города Москвы",
                            Location = "Битцевский проезд",
                            Name = "Велодорожка по Битцевскому проезду",
                            ObjectOperOrgPhone = "(495) 315-50-36",
                            Width = "1.6"
                        },
                        new
                        {
                            Id = 32L,
                            DepartamentalAffiliation = "Префектура Южного административного округа города Москвы",
                            Location = "Коломенская набережная",
                            Name = "Велодорожка по Коломенской набережной",
                            ObjectOperOrgPhone = "(499) 617-21-11",
                            Width = "2.4"
                        },
                        new
                        {
                            Id = 33L,
                            DepartamentalAffiliation = "Префектура Северного административного округа города Москвы",
                            Location = "Большая Академическая улица, дом 22-24",
                            Name = "Велопешеходная зона",
                            ObjectOperOrgPhone = "(985) 640-80-67",
                            Width = "2.1"
                        },
                        new
                        {
                            Id = 34L,
                            DepartamentalAffiliation = "Префектура Северного административного округа города Москвы",
                            Location = "Большая Академическая улица, дом 35",
                            Name = "Велопешеходная зона (в зоне озеленения)",
                            ObjectOperOrgPhone = "(985) 640-80-67",
                            Width = "2.1"
                        },
                        new
                        {
                            Id = 35L,
                            DepartamentalAffiliation = "Префектура Восточного административного округа города Москвы",
                            Location = "Район Богородское",
                            Name = "Велосипедная дорожка",
                            ObjectOperOrgPhone = "(495) 195-82-47",
                            Width = "1.5"
                        },
                        new
                        {
                            Id = 36L,
                            DepartamentalAffiliation = "Префектура Восточного административного округа города Москвы",
                            Location = "Район Гольяново ВАО г. Москвы",
                            Name = "Велосипедная дорожка",
                            ObjectOperOrgPhone = "(495) 469-82-81",
                            Width = "1.5"
                        },
                        new
                        {
                            Id = 37L,
                            DepartamentalAffiliation = "Префектура Северного административного округа города Москвы",
                            Location = "улица Большая Академическая, дом 12, корп. 1",
                            Name = "Велосипедная дорожка",
                            ObjectOperOrgPhone = "(985) 640-80-67",
                            Width = "2.1"
                        },
                        new
                        {
                            Id = 38L,
                            DepartamentalAffiliation = "Префектура Восточного административного округа города Москвы",
                            Location = "Район Ивановское",
                            Name = "Велосипедная дорожка",
                            ObjectOperOrgPhone = "(495) 307-84-91",
                            Width = "1.5"
                        },
                        new
                        {
                            Id = 39L,
                            DepartamentalAffiliation = "Префектура Восточного административного округа города Москвы",
                            Location = "Район Новокосино",
                            Name = "Велосипедная дорожка",
                            ObjectOperOrgPhone = "(495) 701-07-35",
                            Width = "1.5"
                        },
                        new
                        {
                            Id = 40L,
                            DepartamentalAffiliation = "Префектура Восточного административного округа города Москвы",
                            Location = "Район Ивановское",
                            Name = "Велосипедная дорожка",
                            ObjectOperOrgPhone = "(495) 307-84-91",
                            Width = "1.5"
                        },
                        new
                        {
                            Id = 41L,
                            DepartamentalAffiliation = "Префектура Восточного административного округа города Москвы",
                            Location = "Район Измайлово",
                            Name = "Велосипедная дорожка",
                            ObjectOperOrgPhone = "(499) 165-39-91",
                            Width = "2.2"
                        },
                        new
                        {
                            Id = 42L,
                            DepartamentalAffiliation = "Префектура Северного административного округа города Москвы",
                            Location = "Большая Академическая улица, дом 6",
                            Name = "Велосипедная дорожка (в зоне озеленения)",
                            ObjectOperOrgPhone = "(985) 640-80-67",
                            Width = "2.1"
                        },
                        new
                        {
                            Id = 43L,
                            DepartamentalAffiliation = "Префектура Северного административного округа города Москвы",
                            Location = "Большая Академическая улица, дом 18А-20",
                            Name = "Велосипедная дорожка (зона озеленения)",
                            ObjectOperOrgPhone = "(985) 640-80-67",
                            Width = "2.1"
                        },
                        new
                        {
                            Id = 44L,
                            DepartamentalAffiliation = "Префектура Западного административного округа города Москвы",
                            Location = "от ул. Осенняя до Пр-д от ул. Крылатские холмы до ул. Крылатская",
                            Name = "Велосипедная дорожка в Народном парке Крылатское",
                            ObjectOperOrgPhone = "(495) 413-26-14",
                            Width = "2"
                        },
                        new
                        {
                            Id = 45L,
                            DepartamentalAffiliation = "Префектура Западного административного округа города Москвы",
                            Location = "Парк 60 лет Октября",
                            Name = "Велосипедная дорожка в Парке 60 лет Октября",
                            ObjectOperOrgPhone = "(499) 792-45-37",
                            Width = "1"
                        },
                        new
                        {
                            Id = 46L,
                            DepartamentalAffiliation = "Департамент культуры города Москвы",
                            Location = "Парк Победы на Поклонной горе, з/у 1",
                            Name = "Велосипедная дорожка в Парке Победы на Поклонной горе",
                            ObjectOperOrgPhone = "(499) 148-83-00",
                            Width = "1"
                        },
                        new
                        {
                            Id = 47L,
                            DepartamentalAffiliation = "Префектура Северного административного округа города Москвы",
                            Location = "Большая Академическая улица, дом 4",
                            Name = "Велосипедная дорожка в зоне озеленения",
                            ObjectOperOrgPhone = "(985) 640-80-67",
                            Width = "2.1"
                        },
                        new
                        {
                            Id = 48L,
                            DepartamentalAffiliation = "Префектура Юго-Восточного административного округа города Москвы",
                            Location = "Парк 850-летия",
                            Name = "Велосипедная дорожка в парке 850 летия",
                            ObjectOperOrgPhone = "(495) 351-19-91",
                            Width = "3.5"
                        },
                        new
                        {
                            Id = 49L,
                            DepartamentalAffiliation = "Префектура Юго-Восточного административного округа города Москвы",
                            Location = "Парк им.Артёма Боровика",
                            Name = "Велосипедная дорожка в парке им. Артема Боровика",
                            ObjectOperOrgPhone = "(495) 351-19-91",
                            Width = "3.5"
                        },
                        new
                        {
                            Id = 50L,
                            DepartamentalAffiliation = "Префектура Юго-Восточного административного округа города Москвы",
                            Location = "в парке на набережной Москвы-Реки в Капотни",
                            Name = "Велосипедная дорожка в парке на набережной Москвы-Реки в Капотни",
                            ObjectOperOrgPhone = "(495) 355-75-92",
                            Width = "1.5"
                        },
                        new
                        {
                            Id = 51L,
                            DepartamentalAffiliation = "Префектура Северо-Западного административного округа города Москвы",
                            Location = "ул. Героев Панфиловцев, д. 22, корп. 1",
                            Name = "Велосипедная дорожка в сквере по адресу ул. Героев Панфиловцев, д. 22, корп. 1",
                            ObjectOperOrgPhone = "(495) 496-46-92",
                            Width = "0.8"
                        },
                        new
                        {
                            Id = 52L,
                            DepartamentalAffiliation = "Префектура Западного административного округа города Москвы",
                            Location = "улица Мосфильмовская от дома 2 до дома 17/25",
                            Name = "Велосипедная дорожка вдоль улицы Мосфильмовская",
                            ObjectOperOrgPhone = "(499) 792-65-06",
                            Width = "2"
                        },
                        new
                        {
                            Id = 53L,
                            DepartamentalAffiliation = "Префектура Северо-Западного административного округа города Москвы",
                            Location = "Пятницкое шоссе от д.7 до д.23",
                            Name = "Велосипедная дорожка на бульварной зоне по Пятницкому шоссе",
                            ObjectOperOrgPhone = "(495) 753-12-22",
                            Width = "3.5"
                        },
                        new
                        {
                            Id = 54L,
                            DepartamentalAffiliation = "Префектура Северо-Западного административного округа города Москвы",
                            Location = "от дома №29 до дома №39 по Пятницкому шоссе",
                            Name = "Велосипедная дорожка на бульварной зоне №3 по Пятницкому шоссе",
                            ObjectOperOrgPhone = "(495) 753-12-22",
                            Width = "2.5"
                        },
                        new
                        {
                            Id = 55L,
                            DepartamentalAffiliation = "Префектура Северо-Западного административного округа города Москвы",
                            Location = "от дома №41 до дома №47 по Пятницкому шоссе",
                            Name = "Велосипедная дорожка на бульварной зоне №4 по Пятницкому шоссе",
                            ObjectOperOrgPhone = "(495) 753-12-22",
                            Width = "2"
                        },
                        new
                        {
                            Id = 56L,
                            DepartamentalAffiliation = "Префектура Северо-Западного административного округа города Москвы",
                            Location = "территория Березовой рощи (между ул. 3-я Хорошевская д. 5-9 и Новохорошевским проездом д. 8-10)",
                            Name = "Велосипедная дорожка на территории Березовой рощи (между ул. 3-я Хорошевская д. 5-9 и Новохорошевским проездом д. 8-10)",
                            ObjectOperOrgPhone = "(499) 191-40-86",
                            Width = "1.1"
                        },
                        new
                        {
                            Id = 57L,
                            DepartamentalAffiliation = "Префектура Северо-Западного административного округа города Москвы",
                            Location = "Левый берег реки Сходня",
                            Name = "Велосипедная дорожка на территории набережной-сквера вдоль левого берега реки Сходня",
                            ObjectOperOrgPhone = "(499) 492-29-36",
                            Width = "1.1"
                        },
                        new
                        {
                            Id = 58L,
                            DepartamentalAffiliation = "Департамент жилищно-коммунального хозяйства и благоустройства города Москвы",
                            Location = "площадь Джавахарлала Неру, дом 1 - Вернадского проспект дом 12",
                            Name = "Вернадского проспект",
                            ObjectOperOrgPhone = "(495) 940-06-94",
                            Width = "2.5"
                        },
                        new
                        {
                            Id = 59L,
                            DepartamentalAffiliation = "Департамент жилищно-коммунального хозяйства и благоустройства города Москвы",
                            Location = "Воробьёвская набережная, дом 1",
                            Name = "Воробьевская набережная",
                            ObjectOperOrgPhone = "(495) 940-06-94",
                            Width = "3"
                        },
                        new
                        {
                            Id = 60L,
                            DepartamentalAffiliation = "Департамент культуры города Москвы",
                            Location = "улица Косыгина, дом 28",
                            Name = "Воробьёвская набережная, Природный заказник «Воробьёвы горы»",
                            ObjectOperOrgPhone = "(495) 995-00-20",
                            Width = "1.5"
                        },
                        new
                        {
                            Id = 61L,
                            DepartamentalAffiliation = "Префектура Центрального административного округа города Москвы",
                            Location = "Гоголевский б-р",
                            Name = "Гоголевский б-р",
                            ObjectOperOrgPhone = "(495) 670-02-60",
                            Width = "1.2"
                        },
                        new
                        {
                            Id = 62L,
                            DepartamentalAffiliation = "Департамент природопользования и охраны окружающей среды города Москвы",
                            Location = "от улицы Улофа Пальме до улицы Минская",
                            Name = "Долина реки Сетунь",
                            ObjectOperOrgPhone = "(499) 739-27-05",
                            Width = "1.5"
                        },
                        new
                        {
                            Id = 63L,
                            DepartamentalAffiliation = "Департамент природопользования и охраны окружающей среды города Москвы",
                            Location = "от улицы Улофа Пальме до Воробьевского шоссе",
                            Name = "Долина реки Сетунь",
                            ObjectOperOrgPhone = "(499) 739-27-05",
                            Width = "1.5"
                        },
                        new
                        {
                            Id = 64L,
                            DepartamentalAffiliation = "Департамент природопользования и охраны окружающей среды города Москвы",
                            Location = "парк Царицыно",
                            Name = "Долина реки Язвенки (Царицыно)",
                            ObjectOperOrgPhone = "(499) 739-27-05",
                            Width = "1.5"
                        },
                        new
                        {
                            Id = 65L,
                            DepartamentalAffiliation = "Департамент культуры города Москвы",
                            Location = "от улицы Борисовские Пруды и Каширского шоссе до Наташинской улицы",
                            Name = "Зона отдыха Борисовские пруды",
                            ObjectOperOrgPhone = "(499) 175-33-69",
                            Width = "1.5"
                        },
                        new
                        {
                            Id = 66L,
                            DepartamentalAffiliation = "Департамент культуры города Москвы",
                            Location = "аллея Большого Круга, аллея Пролетарского входа",
                            Name = "Измайловский парк",
                            ObjectOperOrgPhone = "(499) 166-61-19",
                            Width = "1.8"
                        },
                        new
                        {
                            Id = 67L,
                            DepartamentalAffiliation = "Департамент культуры города Москвы",
                            Location = "Крымская набережная, владение 2",
                            Name = "Крымская набережная, Музеон",
                            ObjectOperOrgPhone = "(495) 995-00-20",
                            Width = "1.5"
                        },
                        new
                        {
                            Id = 68L,
                            DepartamentalAffiliation = "Департамент жилищно-коммунального хозяйства и благоустройства города Москвы",
                            Location = "Ленинградское шоссе, дом 67 - Ленинградское шоссе, дом 25",
                            Name = "Ленинградское шоссе",
                            ObjectOperOrgPhone = "(495) 940-06-94",
                            Width = "5.4"
                        },
                        new
                        {
                            Id = 69L,
                            DepartamentalAffiliation = "Департамент природопользования и охраны окружающей среды города Москвы",
                            Location = @"от Ярославского шоссе дом 118 до улицы Курганская дом 6
",
                            Name = "Лосиный остров",
                            ObjectOperOrgPhone = "(499) 739-27-05",
                            Width = "1.5"
                        },
                        new
                        {
                            Id = 70L,
                            DepartamentalAffiliation = "Префектура Центрального административного округа города Москвы",
                            Location = "Лужнецкая наб.",
                            Name = "Лужнецкая наб.",
                            ObjectOperOrgPhone = "(495) 670-02-60",
                            Width = "2.5"
                        },
                        new
                        {
                            Id = 71L,
                            DepartamentalAffiliation = "Департамент жилищно-коммунального хозяйства и благоустройства города Москвы",
                            Location = "Люсиновская улица",
                            Name = "Люсиновская улица",
                            ObjectOperOrgPhone = "(495) 940-06-94",
                            Width = "2"
                        },
                        new
                        {
                            Id = 72L,
                            DepartamentalAffiliation = "Департамент культуры города Москвы",
                            Location = "Усадьба «Коломенское», 2-я улица Дьяково-Городище",
                            Name = "Московский государственный объединенный художественный историко-архитектурный и природно-ландшафтный музей-заповедник (МГОМЗ)",
                            ObjectOperOrgPhone = "(499) 612-52-17",
                            Width = "1.5"
                        },
                        new
                        {
                            Id = 73L,
                            DepartamentalAffiliation = "Префектура Центрального административного округа города Москвы",
                            Location = "Неглинная ул.",
                            Name = "Неглинная ул.",
                            ObjectOperOrgPhone = "(495) 670-02-60",
                            Width = "1.2"
                        },
                        new
                        {
                            Id = 74L,
                            DepartamentalAffiliation = "Префектура Центрального административного округа города Москвы",
                            Location = "Никитская Б. ул.",
                            Name = "Никитская Б. ул.",
                            ObjectOperOrgPhone = "(495) 670-02-60",
                            Width = "1.2"
                        },
                        new
                        {
                            Id = 75L,
                            DepartamentalAffiliation = "Префектура Центрального административного округа города Москвы",
                            Location = "Никитская М. ул.",
                            Name = "Никитская М. ул.",
                            ObjectOperOrgPhone = "(495) 670-02-60",
                            Width = "1.2"
                        },
                        new
                        {
                            Id = 76L,
                            DepartamentalAffiliation = "Префектура Центрального административного округа города Москвы",
                            Location = "Никитский б-р",
                            Name = "Никитский б-р",
                            ObjectOperOrgPhone = "(495) 670-02-60",
                            Width = "1.2"
                        },
                        new
                        {
                            Id = 77L,
                            DepartamentalAffiliation = "Префектура Центрального административного округа города Москвы",
                            Location = "Никитских ворот пл-дь",
                            Name = "Никитских ворот пл-дь",
                            ObjectOperOrgPhone = "(495) 670-02-60",
                            Width = "2.5"
                        },
                        new
                        {
                            Id = 78L,
                            DepartamentalAffiliation = "Префектура Центрального административного округа города Москвы",
                            Location = "От Новодевичьей наб. до Погодинской ул.",
                            Name = "Новодевичий пр-д",
                            ObjectOperOrgPhone = "(495) 670-02-60",
                            Width = "2.5"
                        },
                        new
                        {
                            Id = 79L,
                            DepartamentalAffiliation = "Префектура Центрального административного округа города Москвы",
                            Location = "Новодевичья наб.",
                            Name = "Новодевичья наб.",
                            ObjectOperOrgPhone = "(495) 670-02-60",
                            Width = "2.5"
                        },
                        new
                        {
                            Id = 80L,
                            DepartamentalAffiliation = "Префектура Центрального административного округа города Москвы",
                            Location = "Новолужнецкий проезд",
                            Name = "Новолужнецкий проезд",
                            ObjectOperOrgPhone = "(495) 670-02-60",
                            Width = "2.5"
                        },
                        new
                        {
                            Id = 81L,
                            DepartamentalAffiliation = "Префектура Северо-Восточного административного округа города Москвы",
                            Location = "от ул. Череповецкая д.4 до ул. Череповецкая д.24",
                            Name = "Озелененная территория по улице Череповецкая",
                            ObjectOperOrgPhone = "(499) 908-80-79",
                            Width = "2"
                        },
                        new
                        {
                            Id = 82L,
                            DepartamentalAffiliation = "Префектура Юго-Западного административного округа города Москвы",
                            Location = "улица Перекопская дом 34 корпус 4",
                            Name = "Парк 70-летия Победы",
                            ObjectOperOrgPhone = "(499) 128-17-63",
                            Width = "1.3"
                        },
                        new
                        {
                            Id = 83L,
                            DepartamentalAffiliation = "Департамент культуры города Москвы",
                            Location = "улица Удальцова, дом 22",
                            Name = "Парк «50-летия Октября»",
                            ObjectOperOrgPhone = "(499) 145-45-05",
                            Width = "2.4"
                        },
                        new
                        {
                            Id = 84L,
                            DepartamentalAffiliation = "Департамент культуры города Москвы",
                            Location = "пересечение улицы Ангарской с улицей Софьи Ковалевской",
                            Name = "Парк «Ангарские пруды»",
                            ObjectOperOrgPhone = "(499) 908-35-00",
                            Width = "1"
                        },
                        new
                        {
                            Id = 85L,
                            DepartamentalAffiliation = "Департамент культуры города Москвы",
                            Location = "улица Руставели, владение 7",
                            Name = "Парк «Гончаровский»",
                            ObjectOperOrgPhone = "(499) 908-35-00",
                            Width = "1"
                        },
                        new
                        {
                            Id = 86L,
                            DepartamentalAffiliation = "Департамент культуры города Москвы",
                            Location = "улица Свободы, владение 50-70",
                            Name = "Парк «Северное Тушино»",
                            ObjectOperOrgPhone = "(495) 640-73-55",
                            Width = "1.5"
                        },
                        new
                        {
                            Id = 87L,
                            DepartamentalAffiliation = "Департамент культуры города Москвы",
                            Location = "Большая Филёвская улица, дом 22, строение 16",
                            Name = "Парк «Фили»",
                            ObjectOperOrgPhone = "(499) 145-00-00",
                            Width = "2"
                        },
                        new
                        {
                            Id = 88L,
                            DepartamentalAffiliation = "Департамент культуры города Москвы",
                            Location = "Москва, Ходынский бульвар, з/у 1",
                            Name = "Парк «Ходынское поле»",
                            ObjectOperOrgPhone = "(495) 657-45-12",
                            Width = "2.5"
                        },
                        new
                        {
                            Id = 89L,
                            DepartamentalAffiliation = "Префектура Северного административного округа города Москвы",
                            Location = "Парк Грачевка",
                            Name = "Парк Грачевка",
                            ObjectOperOrgPhone = "(499) 767-17-93",
                            Width = "2.5"
                        },
                        new
                        {
                            Id = 90L,
                            DepartamentalAffiliation = "Департамент культуры города Москвы",
                            Location = "проспект Андропова, дом 58А",
                            Name = "Парк Садовники",
                            ObjectOperOrgPhone = "(499) 175-33-69",
                            Width = "2"
                        },
                        new
                        {
                            Id = 91L,
                            DepartamentalAffiliation = "Префектура Центрального административного округа города Москвы",
                            Location = "ул. Сущевский вал, 56 (Парк Фестивальный)",
                            Name = "Парк Фестивальный",
                            ObjectOperOrgPhone = "(495) 670-02-60",
                            Width = "2.5"
                        },
                        new
                        {
                            Id = 92L,
                            DepartamentalAffiliation = "Департамент культуры города Москвы",
                            Location = "Коренная улица, дом 8-10",
                            Name = "Парк культуры и отдыха «Перовский»",
                            ObjectOperOrgPhone = "(495) 309-53-42",
                            Width = "1"
                        },
                        new
                        {
                            Id = 93L,
                            DepartamentalAffiliation = "Департамент культуры города Москвы",
                            Location = "улица Сокольнический Вал, дом 1, строение 1",
                            Name = "Парк культуры и отдыха «Сокольники»",
                            ObjectOperOrgPhone = "(499) 268-54-30",
                            Width = "2.4"
                        },
                        new
                        {
                            Id = 94L,
                            DepartamentalAffiliation = "Департамент культуры города Москвы",
                            Location = "от улицы Маршала Захарова, дом 18 до Борисовского проезда, дом 15, корпус 2",
                            Name = "Парк по Борисовским прудам",
                            ObjectOperOrgPhone = "(499) 175-33-69",
                            Width = "1.5"
                        },
                        new
                        {
                            Id = 95L,
                            DepartamentalAffiliation = "Префектура Северо-Восточного административного округа города Москвы",
                            Location = "от Юрловского проезда дом 14 до Сельскохозяйственной дом 64",
                            Name = "Парк поймы реки Чермянка",
                            ObjectOperOrgPhone = "(495) 708-44-69",
                            Width = "2"
                        },
                        new
                        {
                            Id = 96L,
                            DepartamentalAffiliation = "Департамент культуры города Москвы",
                            Location = "Стартовая улица, дом 10",
                            Name = "Парк у Джамгаровского пруда",
                            ObjectOperOrgPhone = "(499) 184-34-22",
                            Width = "1"
                        },
                        new
                        {
                            Id = 97L,
                            DepartamentalAffiliation = "Департамент культуры города Москвы",
                            Location = "аллея Жемчуговой, владение 2",
                            Name = "Парк у прудов «Радуга»",
                            ObjectOperOrgPhone = "(495) 309-53-42",
                            Width = "2.5"
                        },
                        new
                        {
                            Id = 98L,
                            DepartamentalAffiliation = "Префектура Северного административного округа города Москвы",
                            Location = "Парк-усадьба Михалково",
                            Name = "Парк-усадьба Михалково",
                            ObjectOperOrgPhone = "(499) 153-00-12",
                            Width = "2.5"
                        },
                        new
                        {
                            Id = 99L,
                            DepartamentalAffiliation = "Префектура Центрального административного округа города Москвы",
                            Location = "Петровский б-р",
                            Name = "Петровский б-р",
                            ObjectOperOrgPhone = "(495) 670-02-60",
                            Width = "1.2"
                        },
                        new
                        {
                            Id = 100L,
                            DepartamentalAffiliation = "Департамент жилищно-коммунального хозяйства и благоустройства города Москвы",
                            Location = "Площадь Арбатские ворота",
                            Name = "Площадь Арбатские ворота",
                            ObjectOperOrgPhone = "(495) 940-06-94",
                            Width = "1.2"
                        },
                        new
                        {
                            Id = 101L,
                            DepartamentalAffiliation = "Префектура Северо-Восточного административного округа города Москвы",
                            Location = "Вдоль улицы Северодвинской через Пойму реки Яуза вдоль ул. Северодвинская к 91-му километру МКАД",
                            Name = "Пойма реки Яуза вдоль Северодвинской улицы",
                            ObjectOperOrgPhone = "(495) 656-98-51",
                            Width = "2"
                        },
                        new
                        {
                            Id = 102L,
                            DepartamentalAffiliation = "Префектура Центрального административного округа города Москвы",
                            Location = "Покровский б-р",
                            Name = "Покровский б-р",
                            ObjectOperOrgPhone = "(495) 670-02-60",
                            Width = "1.2"
                        },
                        new
                        {
                            Id = 103L,
                            DepartamentalAffiliation = "Префектура Центрального административного округа города Москвы",
                            Location = "Пречистенских ворот пл-дь",
                            Name = "Пречистенских ворот пл-дь",
                            ObjectOperOrgPhone = "(495) 670-02-60",
                            Width = "2.5"
                        },
                        new
                        {
                            Id = 104L,
                            DepartamentalAffiliation = "Префектура Центрального административного округа города Москвы",
                            Location = "Путинковский Б. пер.",
                            Name = "Путинковский Б. пер.",
                            ObjectOperOrgPhone = "(495) 670-02-60",
                            Width = "1.2"
                        },
                        new
                        {
                            Id = 105L,
                            DepartamentalAffiliation = "Департамент культуры города Москвы",
                            Location = "улица Крымский Вал, дом 9",
                            Name = "Пушкинская набережная, Парк Горького",
                            ObjectOperOrgPhone = "(495) 995-00-20",
                            Width = "1.5"
                        },
                        new
                        {
                            Id = 106L,
                            DepartamentalAffiliation = "Префектура Центрального административного округа города Москвы",
                            Location = "От Климентовского пер. до дома №82",
                            Name = "Пятницкая ул.",
                            ObjectOperOrgPhone = "(495) 670-02-60",
                            Width = "2.5"
                        },
                        new
                        {
                            Id = 107L,
                            DepartamentalAffiliation = "Префектура Центрального административного округа города Москвы",
                            Location = "Рождественский б-р",
                            Name = "Рождественский б-р",
                            ObjectOperOrgPhone = "(495) 670-02-60",
                            Width = "1.2"
                        },
                        new
                        {
                            Id = 108L,
                            DepartamentalAffiliation = "Департамент жилищно-коммунального хозяйства и благоустройства города Москвы",
                            Location = "Рублевское шоссе",
                            Name = "Рублевское шоссе",
                            ObjectOperOrgPhone = "(495) 940-06-94",
                            Width = "1.2"
                        },
                        new
                        {
                            Id = 109L,
                            DepartamentalAffiliation = "Департамент жилищно-коммунального хозяйства и благоустройства города Москвы",
                            Location = "Рязанский проспект",
                            Name = "Рязанский проспект",
                            ObjectOperOrgPhone = "(495) 940-06-94",
                            Width = "1.8"
                        },
                        new
                        {
                            Id = 110L,
                            DepartamentalAffiliation = "Префектура Северо-Восточного административного округа города Москвы",
                            Location = "Парк Сад Будущего",
                            Name = "Сад будущего",
                            ObjectOperOrgPhone = "(499) 187-99-86",
                            Width = "3"
                        },
                        new
                        {
                            Id = 111L,
                            DepartamentalAffiliation = "Префектура Северо-Восточного административного округа города Москвы",
                            Location = "вдоль сквера по Северному бульвару с адресной привязкой от Северного бульвара дом 2 до Северного бульвара дом 21",
                            Name = "Северный бульвар",
                            ObjectOperOrgPhone = "(495) 708-44-69",
                            Width = "2"
                        },
                        new
                        {
                            Id = 112L,
                            DepartamentalAffiliation = "Департамент культуры города Москвы",
                            Location = "Сухонская улица, дом 7",
                            Name = "Сквер по Олонецкому проезду",
                            ObjectOperOrgPhone = "(499) 184-34-22",
                            Width = "1"
                        },
                        new
                        {
                            Id = 113L,
                            DepartamentalAffiliation = "Префектура Северо-Восточного административного округа города Москвы",
                            Location = "Парк света по улице Костромская",
                            Name = "Сквер по ул. Костромская",
                            ObjectOperOrgPhone = "(495) 533-00-22",
                            Width = "3"
                        },
                        new
                        {
                            Id = 114L,
                            DepartamentalAffiliation = "Префектура Центрального административного округа города Москвы",
                            Location = "Соймоновский пр-д",
                            Name = "Соймоновский пр-д",
                            ObjectOperOrgPhone = "(495) 670-02-60",
                            Width = "1.2"
                        },
                        new
                        {
                            Id = 115L,
                            DepartamentalAffiliation = "Префектура Троицкого и Новомосковского административных округов города Москвы",
                            Location = "г. Москва, п. Десеновское, ул. 1-я Ватутинская, д. 6, к. 2",
                            Name = "Спортивный парк",
                            ObjectOperOrgPhone = "(495) 902-57-52",
                            Width = "1.2"
                        },
                        new
                        {
                            Id = 116L,
                            DepartamentalAffiliation = "Префектура Центрального административного округа города Москвы",
                            Location = "Сретенский б-р",
                            Name = "Сретенский б-р",
                            ObjectOperOrgPhone = "(495) 670-02-60",
                            Width = "1.2"
                        },
                        new
                        {
                            Id = 117L,
                            DepartamentalAffiliation = "Префектура Центрального административного округа города Москвы",
                            Location = "Сретенских ворот пл-дь",
                            Name = "Сретенских ворот пл-дь",
                            ObjectOperOrgPhone = "(495) 670-02-60",
                            Width = "1.2"
                        },
                        new
                        {
                            Id = 118L,
                            DepartamentalAffiliation = "Префектура Центрального административного округа города Москвы",
                            Location = "Страстной б-р",
                            Name = "Страстной б-р",
                            ObjectOperOrgPhone = "(495) 670-02-60",
                            Width = "1.2"
                        },
                        new
                        {
                            Id = 119L,
                            DepartamentalAffiliation = "Префектура Центрального административного округа города Москвы",
                            Location = "Тверской б-р",
                            Name = "Тверской б-р",
                            ObjectOperOrgPhone = "(495) 670-02-60",
                            Width = "1.2"
                        },
                        new
                        {
                            Id = 120L,
                            DepartamentalAffiliation = "Префектура Центрального административного округа города Москвы",
                            Location = "Трубная площадь",
                            Name = "Трубная площадь",
                            ObjectOperOrgPhone = "(495) 670-02-60",
                            Width = "1.2"
                        },
                        new
                        {
                            Id = 121L,
                            DepartamentalAffiliation = "Префектура Центрального административного округа города Москвы",
                            Location = "Тургеневская площадь",
                            Name = "Тургеневская площадь",
                            ObjectOperOrgPhone = "(495) 670-02-60",
                            Width = "1.2"
                        },
                        new
                        {
                            Id = 122L,
                            DepartamentalAffiliation = "Департамент жилищно-коммунального хозяйства и благоустройства города Москвы",
                            Location = "Ордынка большая улица",
                            Name = "Улица Большая Ордынка",
                            ObjectOperOrgPhone = "(495) 940-06-94",
                            Width = "1.2"
                        },
                        new
                        {
                            Id = 123L,
                            DepartamentalAffiliation = "Департамент культуры города Москвы",
                            Location = "улица Лобачевского/Мичуринский проспект",
                            Name = "Улица Лобачевского/Мичуринский проспект",
                            ObjectOperOrgPhone = "(499) 145-45-05",
                            Width = "2.5"
                        },
                        new
                        {
                            Id = 124L,
                            DepartamentalAffiliation = "Департамент жилищно-коммунального хозяйства и благоустройства города Москвы",
                            Location = "Территория МГУ на Воробьевых горах",
                            Name = "Университетская площадь",
                            ObjectOperOrgPhone = "(495) 940-06-94",
                            Width = "1.8"
                        },
                        new
                        {
                            Id = 125L,
                            DepartamentalAffiliation = "Департамент культуры города Москвы",
                            Location = "Алтуфьевское шоссе, дом 147 - 149",
                            Name = "Усадьба «Алтуфьево»",
                            ObjectOperOrgPhone = "(499) 908-35-00",
                            Width = "1.6"
                        },
                        new
                        {
                            Id = 126L,
                            DepartamentalAffiliation = "Префектура Центрального административного округа города Москвы",
                            Location = "Фрунзенская наб.",
                            Name = "Фрунзенская наб.",
                            ObjectOperOrgPhone = "(495) 670-02-60",
                            Width = "2.5"
                        },
                        new
                        {
                            Id = 127L,
                            DepartamentalAffiliation = "Префектура Центрального административного округа города Москвы",
                            Location = "Чистопрудный б-р",
                            Name = "Чистопрудный б-р",
                            ObjectOperOrgPhone = "(495) 670-02-60",
                            Width = "1.2"
                        },
                        new
                        {
                            Id = 128L,
                            DepartamentalAffiliation = "Префектура Центрального административного округа города Москвы",
                            Location = "Яузский бульвар",
                            Name = "Яузский бульвар",
                            ObjectOperOrgPhone = "(495) 670-02-60",
                            Width = "1.2"
                        },
                        new
                        {
                            Id = 129L,
                            DepartamentalAffiliation = "Префектура Троицкого и Новомосковского административных округов города Москвы",
                            Location = "г. Москва, г. Троицк, ул. Октябрьский проспект",
                            Name = "велодорожка вдоль Октябрьского проспекта г. Троицк",
                            ObjectOperOrgPhone = "(926) 095-83-50",
                            Width = "2.3"
                        },
                        new
                        {
                            Id = 130L,
                            DepartamentalAffiliation = "Префектура Троицкого и Новомосковского административных округов города Москвы",
                            Location = "г. Москва, г. Троицк, ул. Солнечная",
                            Name = "велодорожка вдоль ул. Солнечная г. Троицк",
                            ObjectOperOrgPhone = "(926) 095-83-50",
                            Width = "2.3"
                        },
                        new
                        {
                            Id = 131L,
                            DepartamentalAffiliation = "Префектура Троицкого и Новомосковского административных округов города Москвы",
                            Location = "г. Москва, г. Троицк, ул. Октябрьский проспект",
                            Name = "г.о. Троицк, Октябрьский проспект",
                            ObjectOperOrgPhone = "(926) 095-83-50",
                            Width = "1.2"
                        },
                        new
                        {
                            Id = 132L,
                            DepartamentalAffiliation = "Департамент природопользования и охраны окружающей среды города Москвы",
                            Location = "от улицы Островитянова до зоны отдыха Тропарево",
                            Name = "ландшафтный заказник Теплый Стан",
                            ObjectOperOrgPhone = "(499) 739-27-05",
                            Width = "1.5"
                        },
                        new
                        {
                            Id = 133L,
                            DepartamentalAffiliation = "Департамент природопользования и охраны окружающей среды города Москвы",
                            Location = "от улицы Миклухо Маклая до микрорайона Северное Чертаново",
                            Name = "парк Битцевский лес",
                            ObjectOperOrgPhone = "(499) 739-27-05",
                            Width = "1.5"
                        },
                        new
                        {
                            Id = 134L,
                            DepartamentalAffiliation = "Департамент природопользования и охраны окружающей среды города Москвы",
                            Location = "МКАД, 36 км, внешняя сторона",
                            Name = "парк Битцевский лес",
                            ObjectOperOrgPhone = "(499) 739-27-05",
                            Width = "1.5"
                        },
                        new
                        {
                            Id = 135L,
                            DepartamentalAffiliation = "Департамент природопользования и охраны окружающей среды города Москвы",
                            Location = "в границах природно-исторического парка Измайлово",
                            Name = "парк Измайлово",
                            ObjectOperOrgPhone = "(499) 739-27-05",
                            Width = "1.5"
                        },
                        new
                        {
                            Id = 136L,
                            DepartamentalAffiliation = "Департамент природопользования и охраны окружающей среды города Москвы",
                            Location = "в границах природно-исторического парка Кузьминки-Люблино",
                            Name = "парк Кузьминки-Люблино",
                            ObjectOperOrgPhone = "(495) 940-06-94",
                            Width = "1.5"
                        },
                        new
                        {
                            Id = 137L,
                            DepartamentalAffiliation = "Департамент природопользования и охраны окружающей среды города Москвы",
                            Location = "на территории лесопарка Кусково",
                            Name = "парк Кусково",
                            ObjectOperOrgPhone = "(499) 739-27-05",
                            Width = "1.5"
                        },
                        new
                        {
                            Id = 138L,
                            DepartamentalAffiliation = "Департамент природопользования и охраны окружающей среды города Москвы",
                            Location = "от Иваньковского шоссе до Никольского тупика",
                            Name = "парк Покровское-Стрешнево",
                            ObjectOperOrgPhone = "(499) 739-27-05",
                            Width = "3.1"
                        },
                        new
                        {
                            Id = 139L,
                            DepartamentalAffiliation = "Префектура Троицкого и Новомосковского административных округов города Москвы",
                            Location = "г. Москва, от ст. Филатов луг до мкр. Первый Московский, ул. Радужная д.1",
                            Name = "парк Филатов Луг",
                            ObjectOperOrgPhone = "(495) 620-20-00",
                            Width = "1.2"
                        },
                        new
                        {
                            Id = 140L,
                            DepartamentalAffiliation = "Департамент жилищно-коммунального хозяйства и благоустройства города Москвы",
                            Location = "микрорайон Ленинские Горы, дом 1 строение 43 - микрорайон Ленинские Горы, дом 1 строение 2",
                            Name = "улица Академика Хохлова",
                            ObjectOperOrgPhone = "(495) 940-06-94",
                            Width = "1.8"
                        },
                        new
                        {
                            Id = 141L,
                            DepartamentalAffiliation = "Префектура Юго-Западного административного округа города Москвы",
                            Location = "улица Миклухо-Маклая",
                            Name = "улица Миклухо-Маклая",
                            ObjectOperOrgPhone = "(499) 128-17-63",
                            Width = "2.3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
