// <auto-generated />
using BIKESobj.InfrastructureServices.Gateways.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BIKESobj.WebService.Migrations
{
    [DbContext(typeof(BIKESobjContext))]
    [Migration("20200603142238_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("BIKESobj.DomainObjects.bikeobj", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PathLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("PathType")
                        .HasColumnType("TEXT");

                    b.Property<string>("PathWeidth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BIKESobjs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "А/д Боровское шоссе – Киевское шоссе – д. Ботаково",
                            PathLocation = "ТиНАО, посел. Первомайское, М-3 Украина- г.Троицк (М-1 Беларусь-Крекшино-Троицк)",
                            PathType = "Велопешеходная дорожка с совмещенным движением,велосипедная полоса попутного движения,Двустороняя велополоса",
                            PathWeidth = "1.8 M",
                            Telephone = "(495) 940-06-94"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Андреевская набережная, Природный заказник «Воробьёвы горы»",
                            PathLocation = "улица Крымский Вал, дом 9",
                            PathType = "велосипедная дорожка двухстороннего движения",
                            PathWeidth = "1.5 M",
                            Telephone = "(495) 995-00-20"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Арбатская площадь",
                            PathLocation = "Арбатская площадь",
                            PathType = "Велопешеходная дорожка с совмещенным движением,велосипедная полоса попутного движения,велосипедная дорожка одностороннего движения",
                            PathWeidth = "1.2 M",
                            Telephone = "(495) 940-06-94"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Березовая аллея",
                            PathLocation = "от Олонецкой улицы дом 15Б до Березовой аллеи дом 7",
                            PathType = "велосипедная дорожка одностороннего движения",
                            PathWeidth = "1 M",
                            Telephone = "(495) 708-44-69"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
